Fix mixed received and transmitted packages with same transfer id can not be parsed correctly
UAVCAN/gui_tool pull request #43
Opened 2020-09-04 05:24 UTC by jxltom

When same kind of packages are send and received at the same time, the parser might not be able to parse the message since the header or the tail of the messages might belong to messages with different directions.

This PR fixes this issue.

2020-09-04 05:26 UTC, jxltom commented
Here is an example to reproduce the issue.

![image](https://user-images.githubusercontent.com/1401630/92202725-2e80be00-eeb2-11ea-93b3-69a8b540b268.png)

2020-09-04 17:09 UTC, pavel-kirienko requested changes
You don't seem to be handling the case where `row_to_frame()` returns None properly. It would raise an error at the tuple unpacking.

2020-09-05 01:04 UTC, jxltom commented
Indeed, thanks for review.

2020-09-05 02:11 UTC, pavel-kirienko approved these changes

2020-09-05 02:11 UTC, merged