Add Actuator Panel
UAVCAN/gui_tool pull request #48
Opened 2021-01-05 03:43 UTC by magicrub

This adds an Actuator Panel which looks very similar to the ESC Panel.

![image](https://user-images.githubusercontent.com/4782875/103603983-ba3c4280-4ec4-11eb-9896-fea526e06489.png)

2021-01-05 08:50 UTC, pavel-kirienko commented
Hi Tom!

It would appear that @polarisru is also working on a similar thing concurrently:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/3298404/103625317-7b010680-4f43-11eb-9e71-67225e67cddc.png">

Alex, would you like to provide any input here or should I just merge it right away?

2021-01-05 09:00 UTC, pavel-kirienko requested changes
This codebase is slowly falling into a state of mild deterioration because the UAVCAN dev team has been mostly focused on [releasing the stable version of the protocol and building the ecosystem around it](https://forum.uavcan.org/t/2020-recap-and-roadmap/1051). This tool has never been intended as a long-term solution so it's missing key components necessary for any well-maintained project like well-defined policies on accepting contributions and releasing new versions. All this means that I am going to accept this changeset (once the minor issues I highlighted here are addressed) without much testing and I am not sure if I am going to be able to build and publish new release binaries with this changeset in place.

2021-01-05 09:04 UTC, Polarisru commented
Yes, you are right :)
Here is my actuator panel looks like:
![actuator](https://user-images.githubusercontent.com/5829978/103626934-2e1a3180-4f3d-11eb-81b4-f0caf10c0ef7.png)
It's up to you, I also will add some product-specific extra features there, but in another panel, this one stays compatible with UAVCANv0 for actuators.

2021-01-05 09:23 UTC, pavel-kirienko commented
Okay. I am inclined to prefer Tom's version then, if only because he got here first.

2021-01-05 09:25 UTC, Polarisru commented
> 
> 
> Okay. I am inclined to prefer Tom's version then, if only because he got here first.

Ok, no problem, but my version has position readout functionality

2021-01-05 09:28 UTC, pavel-kirienko commented
I don't think it's that important either way because UAVCAN v0 in general and this tool in particular are not expected to stay relevant for much longer.

2021-01-05 09:45 UTC, Polarisru commented
Ok, we have a lot of UAVCAN v0 servos already and have to support them, so I will continue to improve this tool anyway.

2021-01-05 12:25 UTC, magicrub reviewed
Thanks for finding those. They were embarrassing enough that I squash it into the same commit :)

2021-01-05 12:25 UTC, magicrub commented on uavcan_gui_tool/panels/acturator_panel.py
> +# Author: Tom Ptttenger <magicrub@gmail.com>
how the hell did I spell my name wrong?!?!?!? Thanks for finding this

2021-01-05 12:25 UTC, magicrub commented on uavcan_gui_tool/panels/__init__.py
> +from . import acturator_panel
fixed

2021-01-05 12:26 UTC, magicrub commented
fixed up. Thanks for the review @pavel-kirienko

2021-01-05 12:27 UTC, magicrub commented
Also, the latest Windows release is quite old. It doesn't support custom dsdl. I would appreciate a new release pretty please.

2021-01-05 12:30 UTC, pavel-kirienko approved these changes

2021-01-05 12:30 UTC, merged

2021-01-06 00:57 UTC, davidbitton commented
do these changes propagate to the pip installed version?

2021-01-06 06:43 UTC, pavel-kirienko commented
No. I might look into that next week.

On Wed, Jan 6, 2021, 02:58 David B. Bitton <notifications@github.com> wrote:

> do these changes propagate to the pip installed version?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/UAVCAN/gui_tool/pull/48#issuecomment-754995697>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZFIZENU55PYMX67NNWP43SYOYRZANCNFSM4VUETJ7A>
> .
>